---
- name: Build metalbox container image
  hosts: all

  tasks:
    - name: Create registry volume
      community.docker.docker_volume:
        name: registry

    - name: Run local container registry
      community.docker.docker_container:
        name: registry
        image: registry:3
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        volumes:
          - registry:/var/lib/registry
